API implementation
Ar2emis/RubyToDoListAPI pull request #1
Opened 2020-10-25 23:42 UTC by ar2em1s

2020-11-05 10:44 UTC, dmitrybereza requested changes

2020-11-05 11:50 UTC, exposwingie approved these changes
Looks good! Some comments below

2020-11-05 12:10 UTC, dmitrybereza approved these changes
![wow](https://user-images.githubusercontent.com/48834312/98239447-a5990800-1f70-11eb-954c-17c4111976e9.jpg)

2020-11-13 13:52 UTC, rostikkkk2 requested changes
<img width="1771" alt="Снимок экрана 2020-11-11 в 21 16 18" src="https://user-images.githubusercontent.com/31447852/99079096-1fac3b00-25c8-11eb-967d-f2baf96cf2ee.png">

fix it please

2020-11-23 13:03 UTC, rostikkkk2 requested changes

2020-11-30 15:40 UTC, rostikkkk2 approved these changes

2020-12-06 16:34 UTC, merged